
// External kernels generated by Allo
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <type_traits>
#include <aie_api/aie.hpp>
#include "layer_norm_bf16_.cc"
#include "aie2/zero.cc"

extern "C" {

void fill_zeros_bf16_4_768_vector(bfloat16 *A) {
  zero_vectorized<bfloat16, 4, 768>(A);
}

} // extern "C"

