
// External kernels generated by Allo
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <type_traits>
#include <aie_api/aie.hpp>
#include "layer_norm_.cc"
#include "aie2/zero.cc"

extern "C" {

void fill_zeros_f32_4_768_vector(float *A) {
  zero_vectorized<float, 4, 768>(A);
}

} // extern "C"

