
// External kernels generated by Allo
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <type_traits>
#include <aie_api/aie.hpp>
#include "aie2/add.cc"

extern "C" {

void add_f32_vector(float *A_in, float *B_in, float *C_out) {
  eltwise_vadd<float, float, 3072>(A_in, B_in, C_out);
}

} // extern "C"

