
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7C400, LENGTH = 0x3C00
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x40400;
fifo_19_buff_0 = .;
. += 0x2000;
. = 0x42400;
fifo_19_buff_1 = .;
. += 0x2000;
. = 0x44400;
fifo_10_cons_buff_0 = .;
. += 0x2000;
. = 0x46400;
fifo_10_cons_buff_1 = .;
. += 0x2000;
. = 0x48400;
fifo_0_1_cons_buff_0 = .;
. += 0x2000;
. = 0x4A400;
fifo_0_1_cons_buff_1 = .;
. += 0x2000;
. = 0x50400;
fifo_15_buff_0 = .;
. += 0x2000;
. = 0x52400;
fifo_15_buff_1 = .;
. += 0x2000;
. = 0x54400;
fifo_6_cons_buff_0 = .;
. += 0x2000;
. = 0x56400;
fifo_6_cons_buff_1 = .;
. += 0x2000;
. = 0x58400;
fifo_2_2_cons_buff_0 = .;
. += 0x2000;
. = 0x5A400;
fifo_2_2_cons_buff_1 = .;
. += 0x2000;
. = 0x70400;
fifo_20_buff_0 = .;
. += 0x2000;
. = 0x72400;
fifo_20_buff_1 = .;
. += 0x2000;
. = 0x74400;
fifo_11_cons_buff_0 = .;
. += 0x2000;
. = 0x76400;
fifo_11_cons_buff_1 = .;
. += 0x2000;
. = 0x78400;
fifo_0_3_cons_buff_0 = .;
. += 0x2000;
. = 0x7A400;
fifo_0_3_cons_buff_1 = .;
. += 0x2000;
  .bss : { *(.bss*) } > data
}
INPUT(external0.o)
PROVIDE(main = core_1_4);
