
// External kernels generated by Allo
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <type_traits>
#include <aie_api/aie.hpp>
#include "attn_out_.cc"
#include "aie2/add.cc"
#include "aie2/zero.cc"

extern "C" {

void fill_zeros_bf16_32_64_vector(bfloat16 *A) {
  zero_vectorized<bfloat16, 32, 64>(A);
}

void add_bf16_vector(bfloat16 *A_in, bfloat16 *B_in, bfloat16 *C_out) {
  eltwise_vadd<bfloat16, bfloat16, 2048>(A_in, B_in, C_out);
}

} // extern "C"

