
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7D400, LENGTH = 0x2C00
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x4C400;
fifo_9_buff_0 = .;
. += 0x800;
. = 0x4CC00;
fifo_9_buff_1 = .;
. += 0x800;
. = 0x40400;
fifo_4_cons_buff_0 = .;
. += 0x3000;
. = 0x43400;
fifo_4_cons_buff_1 = .;
. += 0x3000;
. = 0x46400;
fifo_0_2_cons_buff_0 = .;
. += 0x3000;
. = 0x49400;
fifo_0_2_cons_buff_1 = .;
. += 0x3000;
/* No tile with memory exists to the west. */
. = 0x50000;
. += 0x10000;
/* No tile with memory exists to the north. */
. = 0x60000;
. += 0x10000;
. = 0x7C400;
fifo_10_buff_0 = .;
. += 0x800;
. = 0x7CC00;
fifo_10_buff_1 = .;
. += 0x800;
. = 0x70400;
fifo_5_cons_buff_0 = .;
. += 0x3000;
. = 0x73400;
fifo_5_cons_buff_1 = .;
. += 0x3000;
. = 0x76400;
fifo_0_1_cons_buff_0 = .;
. += 0x3000;
. = 0x79400;
fifo_0_1_cons_buff_1 = .;
. += 0x3000;
  .bss : { *(.bss*) } > data
}
INPUT(external0.o)
PROVIDE(main = core_0_5);
