
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x74840, LENGTH = 0xB7C0
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
. = 0x54800;
fifo_32_buff_0 = .;
. += 0x20;
. = 0x54820;
fifo_32_buff_1 = .;
. += 0x20;
. = 0x54400;
fifo_20_14_cons_buff_0 = .;
. += 0x200;
. = 0x54600;
fifo_20_14_cons_buff_1 = .;
. += 0x200;
. = 0x50400;
fifo_10_cons_buff_0 = .;
. += 0x2000;
. = 0x52400;
fifo_10_cons_buff_1 = .;
. += 0x2000;
. = 0x64800;
fifo_38_buff_0 = .;
. += 0x20;
. = 0x64820;
fifo_38_buff_1 = .;
. += 0x20;
. = 0x64400;
fifo_20_7_cons_buff_0 = .;
. += 0x200;
. = 0x64600;
fifo_20_7_cons_buff_1 = .;
. += 0x200;
. = 0x60400;
fifo_16_cons_buff_0 = .;
. += 0x2000;
. = 0x62400;
fifo_16_cons_buff_1 = .;
. += 0x2000;
. = 0x74800;
fifo_37_buff_0 = .;
. += 0x20;
. = 0x74820;
fifo_37_buff_1 = .;
. += 0x20;
. = 0x74400;
fifo_20_0_cons_buff_0 = .;
. += 0x200;
. = 0x74600;
fifo_20_0_cons_buff_1 = .;
. += 0x200;
. = 0x70400;
fifo_15_cons_buff_0 = .;
. += 0x2000;
. = 0x72400;
fifo_15_cons_buff_1 = .;
. += 0x2000;
  .bss : { *(.bss*) } > data
}
INPUT(external0.o)
PROVIDE(main = core_3_2);
