
// External kernels generated by Allo
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <type_traits>
#include <aie_api/aie.hpp>
#include "aie2/zero.cc"

extern "C" {

void fill_zeros_f32_16_16_vector(float *A) {
  zero_vectorized<float, 16, 16>(A);
}

} // extern "C"

