
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7D040, LENGTH = 0x2FC0
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
. = 0x5D000;
fifo_27_buff_0 = .;
. += 0x20;
. = 0x5D020;
fifo_27_buff_1 = .;
. += 0x20;
. = 0x5C400;
fifo_20_0_cons_buff_0 = .;
. += 0x600;
. = 0x5CA00;
fifo_20_0_cons_buff_1 = .;
. += 0x600;
. = 0x50400;
fifo_5_cons_buff_0 = .;
. += 0x6000;
. = 0x56400;
fifo_5_cons_buff_1 = .;
. += 0x6000;
. = 0x6D000;
fifo_33_buff_0 = .;
. += 0x20;
. = 0x6D020;
fifo_33_buff_1 = .;
. += 0x20;
. = 0x6C400;
fifo_20_4_cons_buff_0 = .;
. += 0x600;
. = 0x6CA00;
fifo_20_4_cons_buff_1 = .;
. += 0x600;
. = 0x60400;
fifo_11_cons_buff_0 = .;
. += 0x6000;
. = 0x66400;
fifo_11_cons_buff_1 = .;
. += 0x6000;
. = 0x7D000;
fifo_32_buff_0 = .;
. += 0x20;
. = 0x7D020;
fifo_32_buff_1 = .;
. += 0x20;
. = 0x7C400;
fifo_20_1_cons_buff_0 = .;
. += 0x600;
. = 0x7CA00;
fifo_20_1_cons_buff_1 = .;
. += 0x600;
. = 0x70400;
fifo_10_cons_buff_0 = .;
. += 0x6000;
. = 0x76400;
fifo_10_cons_buff_1 = .;
. += 0x6000;
  .bss : { *(.bss*) } > data
}
INPUT(external0.o)
PROVIDE(main = core_2_2);
