
// External kernels generated by Allo
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <type_traits>
#include <aie_api/aie.hpp>
#include "aie2/add.cc"

extern "C" {

void add_bf16_vector(bfloat16 *A_in, bfloat16 *B_in, bfloat16 *C_out) {
  eltwise_vadd<bfloat16, bfloat16, 3072>(A_in, B_in, C_out);
}

} // extern "C"

