
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x71C00, LENGTH = 0xE400
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
/* No tile with memory exists to the west. */
. = 0x50000;
. += 0x10000;
. = 0x60400;
fifo_6_buff_0 = .;
. += 0x600;
. = 0x60A00;
fifo_6_buff_1 = .;
. += 0x600;
. = 0x61000;
fifo_1_cons_buff_0 = .;
. += 0x600;
. = 0x61600;
fifo_1_cons_buff_1 = .;
. += 0x600;
. = 0x70400;
fifo_5_buff_0 = .;
. += 0x600;
. = 0x70A00;
fifo_5_buff_1 = .;
. += 0x600;
. = 0x71000;
fifo_0_cons_buff_0 = .;
. += 0x600;
. = 0x71600;
fifo_0_cons_buff_1 = .;
. += 0x600;
  .bss : { *(.bss*) } > data
}
PROVIDE(main = core_0_2);
